---
title: "Rmarkdown"
author: "Oliver"
date: "2021/12/14"
output: html_document
---

```{r}
library(tidyverse)
library(fs)
library(stringr)
library(utils)

listfiles<-dir_info(here::here("data")) %>%
  dplyr::filter(str_detect(path, ".gz")) %>%
  dplyr::select(path)%>%
  dplyr::pull()%>%
  #print out the .gz file
  print()%>%
  as.character()%>%
  utils::untar(exdir=here::here("data"))
```

```{r}
library(sp)
library(raster)
library(rgeos)
library(rgdal)
library(rasterVis)
library(ggplot2)
library(terra)
library(sf)
library(stringr)
library(raster)
library(fs)
library(sf)
library(tidyverse)
```

```{r}
# List your raster files excluding band 8 using the patter argument
listlandsat<-dir_info(here::here("data"))%>%
  dplyr::filter(str_detect(path, "[B123456790].TIF")) %>%
  dplyr::select(path)%>%
  pull()%>%
  as.character()%>%
  # Load our raster layers into a stack
  stack()

# Load the manchester boundary
manchester_boundary <- st_read(here::here("data", 
                                        
                                          "Manchester_boundary.shp"))

crs(manchester_boundary)
crs(listlandsat)
```

```{r}
# get band 8
b8list<-dir_info(here::here("data"))%>%
  dplyr::filter(str_detect(path, "[B8].tif")) %>%
  dplyr::select(path)%>%
  pull()%>%
  as.character()%>%
  raster()
```

```{r}
b8correct <- b8list%>%
  resample(., listlandsat$LC08_L1TP_203023_20190513_20190521_01_T1_B1, 
             method = "ngb") %>%
  # Write out the raster
writeRaster(.,str_c(here::here("data"), 
                  names(b8list), 
                  sep="/"),
            format='GTiff', 
            overwrite=TRUE)
```

```{r}
b8backin<-dir_info(here::here("data"))%>%
  dplyr::filter(str_detect(path, "[B8].tif")) %>%
  dplyr::select(path)%>%
  pull()%>%
  as.character()%>%
  raster()
  
listlandsat <- listlandsat %>%
  addLayer(., b8backin)
```

```{r}
raster::compareRaster(listlandsat$LC08_L1TP_203023_20190513_20190521_01_T1_B1,
              listlandsat$LC08_L1TP_203023_20190513_20190521_01_T1_B8)
```

```{r}
lsatmask <- listlandsat %>%
  # now crop our temp data to the extent
  raster::crop(.,manchester_boundary)%>%
  raster::mask(.,  manchester_boundary)
```

```{r}
# add mask to the filenames within the raster stack

names(lsatmask) <- names(lsatmask)%>%
  str_c(., 
        "mask", 
        sep="_")

# I need to write mine out in another location
outputfilenames <-
  str_c("data/", names(lsatmask) ,sep="")
```

```{r}
lsatmask %>%
  writeRaster(., names(lsatmask), 
              bylayer=TRUE, 
              format='GTiff', 
              overwrite=TRUE)
```

```{r}
lsatmask %>%
  writeRaster(., outputfilenames, 
              bylayer=TRUE, 
              format='GTiff', 
              overwrite=TRUE)
```

```{r}
manc_files<-dir_info(here::here("data")) %>%
  dplyr::filter(str_detect(path, "[B1234567]_mask.tif")) %>%
  dplyr::filter(str_detect(path, "B11", negate=TRUE))%>%
  dplyr::select(path)%>%
  pull()%>%
  stack()

# or extract them from the original stack
manc<-stack(lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B1_mask,
                   lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B2_mask,
                   lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B3_mask,
                   lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B4_mask,
                   lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B5_mask,
                   lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B6_mask,
                   lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B7_mask)

# Name the Bands based on where they sample the electromagentic spectrum
names(manc) <- c('ultra-blue', 'blue', 'green', 'red', 'NIR', 'SWIR1', 'SWIR2')
```

```{r}
# true colour composite
manc_rgb <- stack(manc$red, manc$green, manc$blue)
# false colour composite
manc_false <- stack(manc$NIR, manc$red, manc$green)

manc_rgb %>%
  plotRGB(.,axes=TRUE, stretch="lin")
```

```{r}
manc_false %>%
    plotRGB(.,axes=TRUE, stretch="lin")
```

```{r}
# Looking at single bands
plot(manc$SWIR2)
```

```{r}
## How are these bands different?
#set the plot window size (2 by 2)
par(mfrow = c(2,2))
#plot the bands
plot(manc$blue, main = "Blue")
plot(manc$green, main = "Green")
plot(manc$red, main = "Red")
plot(manc$NIR, main = "NIR")
```

```{r}
library(ggplot2)
library(GGally)

manc %>%
  terra::as.data.frame(., na.rm=TRUE)%>%
  dplyr::sample_n(., 100)%>%
  ggpairs(.,axisLabels="none")
```

```{r}
NDVIfun <- function(NIR, Red) {
  NDVI <- (NIR - Red) / (NIR + Red)
  return(NDVI)
}
source(here::here('data/source.txt'))
```

```{r}
ndvi <- NDVIfun(manc$NIR, manc$red)
ndvi %>%
  plot(.,col = rev(terrain.colors(10)), main = "Landsat-NDVI")
```

```{r}
# Let's look at the histogram for this dataset
ndvi %>%
  hist(., breaks = 40, main = "NDVI Histogram", xlim = c(-.3,.8))
```

```{r}
veg <- ndvi %>%
  reclassify(., cbind(-Inf, 0.3, NA))

veg %>%
  plot(.,main = 'Possible Veg cover')
```

```{r}
manc_rgb %>%
  plotRGB(.,axes = TRUE, stretch = "lin", main = "Landsat True Color Composite")

veg %>%
  plot(., add=TRUE, legend=FALSE)
```

```{r}
manc_rgb %>%
  plotRGB(.,axes = TRUE, stretch = "lin", main = "Landsat True Color Composite")

veg %>%
  plot(., add=TRUE, legend=FALSE)
```

```{r}
library(RStoolbox)

MTL<-dir_info(here::here("data")) %>%
  dplyr::filter(str_detect(path, "MTL.txt")) %>%
  dplyr::select(path)%>%
  pull()%>%
  readMeta()

 #To see all the attributes
head(MTL)
```

```{r}
offsetandgain <-MTL %>%
  getMeta("B10_dn", metaData = ., what = "CALRAD")

offsetandgain
```

```{r}
offsetandgain <- subset(MTL$CALRAD, rownames(MTL$CALRAD) == "B10_dn")
```

```{r}
TOA <- offsetandgain$gain *
  lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B10_mask + 
  offsetandgain$offset
```

```{r}
Calidata <- MTL$CALBT%>%
  terra::as.data.frame()%>%
  mutate(Band=rownames(.))%>%
  filter(Band=="B10_dn")

# subset the columns
K1 <- Calidata %>%
  dplyr::select(K1)%>%
  pull()

K2 <- Calidata %>%
  dplyr::select(K2)%>%
  pull()

Brighttemp <- (K2 / log((K1 / TOA) + 1))
```

```{r}
facveg <- (ndvi-0.2/0.5-0.2)^2
emiss <- 0.004*facveg+0.986
```
```{r}
Boltzmann <- 1.38*10e-23
Plank <- 6.626*10e-34
c <- 2.998*10e8

p <- Plank*(c/Boltzmann)
```

```{r}
#define remaining varaibles
lambda <- 1.09e-5
#run the LST calculation
LST <- Brighttemp/(1 +(lambda*Brighttemp/p)*log(emiss))
# check the values
LST
```

```{r}
LST <- LST-273.15
plot(LST)
```

```{r}
NDBI=((lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B6_mask-
         lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B5_mask)/
        (lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B6_mask+
        lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B5_mask))

NDBIfunexample <- NDVIfun(lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B6_mask,
                          lsatmask$LC08_L1TP_203023_20190513_20190521_01_T1_B5_mask)
```

```{r}
plot(values(NDBI), values(LST))
```

```{r}
# stack the layers

computeddata <- LST%>%
  stack(.,NDBI)%>%
  terra::as.data.frame()%>%
  na.omit()%>%
  # take a random subset
  dplyr::sample_n(., 500)%>%
  dplyr::rename(Temp="layer.1", NDBI="layer.2")

 # check the output
plot(computeddata$Temp, computeddata$NDBI)
```

```{r}
library(plotly)
library(htmlwidgets)
```

```{r}
heat<-ggplot(computeddata, aes(x = NDBI, y = Temp))+
  geom_point(alpha=2, colour = "#51A0D5")+
  labs(x = "Temperature", 
       y = "Urban index",
       title = "Manchester urban and temperature relationship")+
   geom_smooth(method='lm', se=FALSE)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))

# interactive plot
ggplotly(heat)
```

```{r}
computeddatafull <- LST%>%
  stack(.,NDBI)%>%
  terra::as.data.frame()%>%
  na.omit()%>%
  # take a random subset
  dplyr::rename(Temp="layer.1", NDBI="layer.2")

hexbins <- ggplot(computeddatafull, 
                  aes(x=NDBI, y=Temp)) +
  geom_hex(bins=100, na.rm=TRUE) +
  labs(fill = "Count per bin")+
  geom_smooth(method='lm', se=FALSE, size=0.6)+
  theme_bw()

ggplotly(hexbins)
```

```{r}
install.packages("rstatix")
library(rstatix)
Correlation <- computeddatafull %>%
  cor_test(Temp, NDBI, use = "complete.obs", method = c("pearson"))

Correlation
```

```{r}
abs(qt(0.05/2, 198268))
```
```{r}
computeddatafull %>%
  pull(Temp)%>%
  length()

length(computeddatafull)
```
```{r}
library(dplyr)
library(sf)

# read in LSOA data
UK_LSOA <- st_read(here::here("data", 
                                          
                                          "5878ebcf-f091-4bde-8864-aa547dd45afd2020330-1-8g4usn.8evuq.shp"))
```

```{r}
# project it to match Manchester boundary
UK_LSOA <- UK_LSOA %>%
  st_transform(., 32630)

# read in MSOA and project it
MSOA <- st_read(here::here("data",
                           
                           "Middle_Layer_Super_Output_Areas_December_2011_Generalised_Clipped_Boundaries_in_England_and_Wales.shp")) %>%
   st_transform(., 32630)
```

```{r}
#select only MSOA within boundary
manchester_MSOA <- MSOA[manchester_boundary, , op=st_within]

#select only LSOA that intersect MSOA
manchester_LSOA <- UK_LSOA[manchester_MSOA,]
```

```{r}
 
LST_per_LSOA <- raster::extract(LST, manchester_LSOA, fun=mean, na.rm=TRUE, df=TRUE)

# add the LSOA ID back
LST_per_LSOA$FID<-manchester_LSOA$FID

# join the average temp to the sf
manchester_LSOA_temp <- manchester_LSOA %>%
  left_join(.,
            LST_per_LSOA,
            by="FID")%>%
  dplyr::rename(temp=layer)
```

```{r}
#define urban as NDBI greater than 0
NDBI_urban<- NDBI > 0

# Sum the pixels that are grater than 0 per LSOA
NDBI_urban_per_LSOA <- raster::extract(NDBI_urban, manchester_LSOA, na.rm=TRUE, df=TRUE, fun=sum)

# list the pixels per LSOA
NDBI_per_LSOA_cells <- raster::extract(NDBI_urban, manchester_LSOA, na.rm=TRUE, df=TRUE, cellnumbers=TRUE)

#count the pixels per LSOA
NDBI_per_LSOA2_cells<- NDBI_per_LSOA_cells %>%
  count(ID)

#add the LSOA ID to the urban area
NDBI_urban_per_LSOA$FID<-manchester_LSOA$FID

#add the LSOA ID to the number of cells
NDBI_per_LSOA2_cells$FID<-manchester_LSOA$FID

#join these two
Urban_info_LSOA <- NDBI_urban_per_LSOA %>%
  left_join(.,
            NDBI_per_LSOA2_cells,
            by="FID")

# remove what you don't need and rename
Urban_info_LSOA_core_needed <- Urban_info_LSOA %>%
  dplyr::rename(urban_count=layer, 
                LSOA_cells=n) %>%
  dplyr::select(urban_count,
         LSOA_cells,
         FID)%>%
  dplyr::mutate(percent_urban=urban_count/LSOA_cells*100)

# join the data 
# one sf with temp and % urban per LSOA
manchester_LSOA_temp_urban <- manchester_LSOA_temp %>%
  left_join(.,
             Urban_info_LSOA_core_needed,
             by="FID")
```

```{r}
Places <- st_read(here::here("data", 
                                          
                                          "gis_osm_places_free_1.shp")) %>%
   st_transform(., 32630)
```

